### ISSUE TITLE
Recipe does not install aiohttp dependency correctly

### ISSUE THREAD

**Issue by aidanheerdegen** [conda-forge/black-feedstock#19]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

<br/>
Environment (<code>conda list</code>):

<details>

```
$ conda list
# packages in environment at /Users/aidan/miniconda3/envs/blackenv:
#
# Name                    Version                   Build  Channel
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
black                     20.8b1                     py_1    conda-forge
ca-certificates           2020.12.5            h033912b_0    conda-forge
certifi                   2020.12.5        py39h6e9494a_1    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
dataclasses               0.8                pyhc8e2a94_1    conda-forge
libcxx                    11.1.0               habf9029_0    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
mypy_extensions           0.4.3            py39h6e9494a_3    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
openssl                   1.1.1j               hbcf498f_0    conda-forge
pathspec                  0.8.1              pyhd3deb0d_0    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
python                    3.9.2           h2502468_0_cpython    conda-forge
python_abi                3.9                      1_cp39    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
regex                     2020.11.13       py39hcbf5805_1    conda-forge
setuptools                49.6.0           py39h6e9494a_3    conda-forge
sqlite                    3.34.0               h17101e1_0    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
typed-ast                 1.4.2            py39hcbf5805_0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : blackenv
    active env location : /Users/aidan/miniconda3/envs/blackenv
            shell level : 2
       user config file : /Users/aidan/.condarc
 populated config files : /Users/aidan/.condarc
          conda version : 4.8.4
    conda-build version : 3.15.1
         python version : 3.7.2.final.0
       virtual packages : __osx=10.15.6
       base environment : /Users/aidan/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/coecms/osx-64
                          https://conda.anaconda.org/coecms/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/aidan/miniconda3/pkgs
                          /Users/aidan/.conda/pkgs
       envs directories : /Users/aidan/miniconda3/envs
                          /Users/aidan/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.4 requests/2.24.0 CPython/3.7.2 Darwin/19.6.0 OSX/10.15.6
                UID:GID : 504:20
             netrc file : /Users/aidan/.netrc
           offline mode : False
```
</details>

With a minimal environment yaml specification the correct dependencies are not installed:
```yaml
name: blackenv
channels:
- conda-forge
dependencies:
- black
```

```
$ conda env create -f black.yml
$ conda activate blackenv
(blackenv) $ blackd
Traceback (most recent call last):
  File "/Users/aidan/miniconda3/envs/blackenv/bin/blackd", line 7, in <module>
    from blackd import patched_main
  File "/Users/aidan/miniconda3/envs/blackenv/lib/python3.9/site-packages/blackd/__init__.py", line 9, in <module>
    from aiohttp import web
ModuleNotFoundError: No module named 'aiohttp'
```

It seems the recipe is installing `blackd` but not specifying this correctly when invoking `setup.py`. The [docs](https://black.readthedocs.io/en/stable/blackd.html) say

> blackd is not packaged alongside Black by default because it has additional dependencies. You will need to execute `pip install  black[d]` to install it.

But the build script is not doing this:

https://github.com/conda-forge/black-feedstock/blob/master/recipe/build_base.sh#L11

as a result I guess these dependencies (`aiohttp` and `aiohttp-cors`) are not correctly specified:

https://github.com/psf/black/blob/24418a54501381e1cdbe0ab1de4e4ced7537c124/setup.py#L81-L83

**Comment by carlodri** [comment]
have you tried this:

```yml
name: blackenv
channels:
- conda-forge
dependencies:
- blackd
```

(note the `blackd`)

**Comment by carlodri** [comment]
@aidanheerdegen can we close this?

**Comment by aidanheerdegen** [comment]
TBH I can't recall what I did to fix it so yeah can close.
